### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leifdenby** [leifdenby/cmo-workshop-eurec4a#1]
- [ ] calculation dz
- [ ] calculation of density of LWP
- [ ] check that file name convention matches what MARTIN expects
- [x] delete the extra precipitaiton
- [ ] run scripts to all produce plots for both practicals (needs shell script)

From Sam:
- [ ] colormap for cloud type plot
- [ ] how to compute dz
